### ISSUE TITLE
can not download glove.6B.zip

### ISSUE THREAD

**Issue by drawStar** [bentrevett/pytorch-sentiment-analysis#1]
Hi, I have a problem when run this code
TEXT.build_vocab(train, max_size=25000, vectors="glove.6B.100d")
It's outputs as follows:
.vector_cache/glove.6B.zip: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "/home/hang/PycharmProjects/pytorch/test.py", line 20, in <module>
    TEXT.build_vocab(train, max_size=20000, vectors="glove.6B.100d")
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/field.py", line 257, in build_vocab
    self.vocab = self.vocab_cls(counter, specials=specials, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torchtext/vocab.py", line 80, in __init__
    self.load_vectors(vectors, unk_init=unk_init, cache=vectors_cache)
  File "/usr/local/lib/python2.7/dist-packages/torchtext/vocab.py", line 139, in load_vectors
    vectors[idx] = pretrained_aliases[vector](**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torchtext/vocab.py", line 347, in __init__
    super(GloVe, self).__init__(name, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torchtext/vocab.py", line 236, in __init__
    self.cache(name, cache, url=url)
  File "/usr/local/lib/python2.7/dist-packages/torchtext/vocab.py", line 268, in cache
    with zipfile.ZipFile(dest, "r") as zf:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

My system is ubuntu and python2.7, 
Can I download "glove.6B.zip"  manually  ?

**Comment by mayxx** [comment]
how to solve this problem ?

**Comment by mayxx** [comment]
thank you!

**Comment by mayxx** [comment]
but I can not find the folder .vector_cache , already tried locate vector_cache still can not find

**Comment by bentrevett** [comment]
Are you on Linux? Files/folders starting with ‘.’ are hidden by default but you should still be able to delete them.

**Comment by mayxx** [comment]
On Mac OS . these are all I can see by  ls -a
.		__init__.py	data		utils.py	vocab.py
..		__init__.pyc	datasets	utils.pyc	vocab.pyc

**Comment by mayxx** [comment]
Thank you, I solved this problem after running the code on the server and found the folder
