### ISSUE TITLE
A - Using TorchText with Your Own Datasets

### ISSUE THREAD

**Issue by 404akhan** [bentrevett/pytorch-sentiment-analysis#27]
Hi, I tried to use my own dataset. And was getting an error. Suppose my code is following:

```
from torchtext import data
from torchtext import datasets
import torch

NAME = data.Field()
SAYING = data.Field()
PLACE = data.Field()

fields = {'name': ('n', NAME), 'location': ('p', PLACE), 'quote': ('s', SAYING)}

train_data, test_data = data.TabularDataset.splits(
                            path = 'sample_data',
                            train = 'sample_data_train.json',
                            test = 'sample_data_test.json',
                            format = 'json',
                            fields = fields
)

BATCH_SIZE = 64
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


NAME.build_vocab(train_data)
SAYING.build_vocab(train_data)
PLACE.build_vocab(train_data)

train_iterator, test_iterator = data.BucketIterator.splits(
    (train_data, test_data), 
    batch_size=BATCH_SIZE,
    device=device)


for batch in train_iterator:
	print(batch)
for batch in test_iterator:
	print(batch)
```

Where both `sample_data_train.json and sample_data_test.json` refer to json file:
```
{"name": "John", "location": "United Kingdom", "age": 42, "quote": ["i", "love", "the", "united kingdom"]}
{"name": "Mary", "location": "United States", "age": 36, "quote": ["i", "want", "more", "telescopes"]}
```

So this is the basic code which was supposed to run. But I get the following error:
```
[torchtext.data.batch.Batch of size 2]
	[.p]:[torch.LongTensor of size 2x2]
	[.n]:[torch.LongTensor of size 1x2]
	[.s]:[torch.LongTensor of size 4x2]
Traceback (most recent call last):
  File "test5.py", line 35, in <module>
    for batch in test_iterator:
  File "/home/akhan/.local/lib/python3.5/site-packages/torchtext/data/iterator.py", line 142, in __iter__
    self.init_epoch()
  File "/home/akhan/.local/lib/python3.5/site-packages/torchtext/data/iterator.py", line 118, in init_epoch
    self.create_batches()
  File "/home/akhan/.local/lib/python3.5/site-packages/torchtext/data/iterator.py", line 242, in create_batches
    self.batches = batch(self.data(), self.batch_size,
  File "/home/akhan/.local/lib/python3.5/site-packages/torchtext/data/iterator.py", line 103, in data
    xs = sorted(self.dataset, key=self.sort_key)
TypeError: unorderable types: Example() < Example()
```

So code can iterate through train data, but cannot through test data. Can you spot the reason. Thanks!!!

**Comment by AntixK** [comment]
I came across the same problem. Apparently, this occurs due to the type mismatch when comparing the elements for sorting.
I solved it by explicitly providing keys.

```
train_iter, val_iter, test_iter = data.Iterator.splits(
        (train, val, test), sort_key=lambda x: len(x.Text),
         batch_size=BATCH_SIZE,
         device=device)
```

**Comment by bentrevett** [comment]
I don't think this is because of the type mismatch. I think it's because TorchText wants to sort test/validation data within a batch by default.

``` python
train_iterator, valid_iterator, test_iterator = data.BucketIterator.splits(
    (train_data, valid_data, test_data),
    batch_size=BATCH_SIZE,
    device=device)

print(train_iterator.sort) #False
print(valid_iterator.sort) #True
print(test_iterator.sort) #True
```

So it's trying to sort the examples within the batches of the the valid/test iterator, but it doesn't know what to sort them by. The two ways to solve this are using a `sort_key`, as mentioned above, or get rid of sorting in the test/validation sets by passing `sort = False` to the iterator.

``` python
train_iterator, valid_iterator, test_iterator = data.BucketIterator.splits(
    (train_data, valid_data, test_data),
    batch_size=BATCH_SIZE,
    sort=False,
    device=device)
```

You don't have to do this for the IMDb dataset as it already has a default sort key set.

**Comment by bentrevett** [comment]
Updated appendix A with an explanation for how to handle this.

**Comment by 404akhan** [comment]
sorting is done to minimize amount of padding inside each batch, as i understand. So if inside the batch samples have around the same length, then amount of padding is decreased. So, it is better not to turn off sorting.

**Comment by bentrevett** [comment]
Yep, that's correct. I've amended the explanation to mention how using `sort_key` is preferred over `sort = False`.

**Comment by jeremy-rutman** [comment]
>  sort_key=lambda x: len(x.Text),

that's 
`sort_key=lambda x: len(x.text),`   with a lowercase t, btw.
